.common: &common
  services:
  - name: selenium/standalone-firefox
    alias: firefox
  - name: selenium/standalone-chrome
    alias: chrome
  variables:
    WEBDRIVER_HOST_CHROME: chrome:4444
    WEBDRIVER_HOST_FIREFOX: firefox:4444
    TESTRUNNER_HOST: '0.0.0.0'
  script:
  - npm install && npm test --ignore-scripts=false

node:14:
  <<: *common
  image: node:14

node:16:
  <<: *common
  image: node:16

node:17:
  <<: *common
  image: node:18
