.common: &common
  services:
  - name: selenium/standalone-firefox
    alias: firefox
  - name: selenium/standalone-chrome
    alias: chrome
  variables:
    WEBDRIVER_DISABLE_SHM: true
    WEBDRIVER_HOST_CHROME: chrome:4444
    WEBDRIVER_HOST_FIREFOX: firefox:4444
    TESTRUNNER_HOST: '0.0.0.0'
  script:
  - npm install-test

node:16:
  <<: *common
  image: node:16

node:18:
  <<: *common
  image: node:18

node:19:
  <<: *common
  image: node:19
