before_script:
- apt-get update
- wget --no-verbose https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
- apt-get install -y ./google-chrome-stable_current_amd64.deb
- apt-get install -y firefox-esr || apt-get install -y iceweasel

node:14:
  image: node:14
  script:
  - echo "install" && npm install
  - echo "A" && ./src/bin/run.mjs src
  - echo "B" && ./build/bin/run.mjs src
  - echo "package" && ./test/run-package.sh
  - ./src/bin/run.mjs --parallel src && rollup --config rollup.config.js && ./test/run-integration.mjs && ./test/run-package.sh
  - echo "test" && npm test

node:16:
  image: node:16
  script:
  - npm install-test

node:17:
  image: node:17
  script:
  - npm install-test
