.common: &common
  services:
  - name: selenium/standalone-firefox
    alias: firefox
  - name: selenium/standalone-chrome
    alias: chrome
  variables:
    WEBDRIVER_HOST_CHROME: chrome:4444
    WEBDRIVER_HOST_FIREFOX: firefox:4444
    WEBDRIVER_TESTRUNNER_HOST: node
    TESTRUNNER_HOST: '0.0.0.0'
  script:
  - npm install-test --ignore-scripts=false

node:14:
  <<: *common
  image: node:14

node:16:
  <<: *common
  image: node:16

node:17:
  <<: *common
  image: node:17

experiment:
  image: node:17
  services:
  - name: selenium/standalone-firefox
    alias: firefox
  script: |
    set -x
    apt-get update && apt-get install -y jq
    npx http-server . -a 0.0.0.0 -p 8080 &
    sleep 10
    curl http://localhost:8080
    SESSION_ID="$(curl http://firefox:4444/session -d '{"capabilities":{"firstMatch":[{"browserName":"firefox"}]}}' | jq '.value.sessionId')"
    echo "Session ID: $SESSION_ID"
    curl http://firefox:4444/session/$SESSION_ID/url -d '{"url":"http://example.com"}'
    curl http://firefox:4444/session/$SESSION_ID/url -d '{"url":"http://localhost:8080"}'
    curl http://firefox:4444/session/$SESSION_ID/url -d '{"url":"http://experiment:8080"}'
    curl http://firefox:4444/session/$SESSION_ID/url -d '{"url":"http://127.0.0.1:8080"}'
    curl http://firefox:4444/session/$SESSION_ID/url -d '{"url":"http://0.0.0.0:8080"}'
    curl http://firefox:4444/session/$SESSION_ID/url -d '{"url":"http://[::1]:8080"}'
    curl http://firefox:4444/session/$SESSION_ID/url -d '{"url":"http://[::]:8080"}'
