export const primitiveValueFactories: (() => unknown)[] = [
	() => +0,
	() => +1,
	() => -0,
	() => -1,
	() => 0 / 0,
	() => 1 / 0,
	() => -1 / 0,
	() => 0.1,
	() => 7,
	() => Math.PI,
	() => 0n,
	() => 10n,
	() => null,
	() => undefined,
	() => true,
	() => false,
	() => 'foo',
	() => '',
	() => '0',
	() => 'NaN',
	() => 'null',
	() => 'undefined',
];

const COMMON_SYMBOL = Symbol('key');

export const standardValueFactories: (() => unknown)[] = [
	() => ({}),
	() => ({ foo: 'bar' }),
	() => ({ foo: 'zag' }),
	() => ({ foo: 'bar', zig: 'zag' }),
	() => ({ foo: { bar: 'baz' } }),
	() => ({ foo: { bar: 'baz', zig: 'zag' } }),
	() => ({ foo: { zag: 'baz' } }),
	() => ({ foo: { bar: 'zag' } }),
	() => ({ [COMMON_SYMBOL]: 'foo' }),
	() => ({ [COMMON_SYMBOL]: 'bar' }),
	() => ({ 0: 0 }),
	() => ({ 0: 0, length: 1 }),
	() => ({ length: 0, size: 0, foo: 'bar' }),
	() => ({ length: 0 }),
	() => ({ size: 0 }),
	() => [],
	() => [0],
	() => [undefined],
	() => [, undefined],
	() => [0, ,],
	() => new Array(1),
	() => Object.assign([0], { foo: 'bar' }),
	() => Object.assign([0], { 2: 'bar' }),
	() => Object.assign([0], { '-1': 'bar' }),
	() => Object.assign([0], { [COMMON_SYMBOL]: 'a' }),
	() => Object.assign([0], { [COMMON_SYMBOL]: 'b' }),
	() => ['foo'],
	() => ['foo', 'bar'],
	() => ['bar', 'foo'],
	() => /foo/,
	() => /bar/,
	() => /foo/i,
	() => new Date(),
	() => new Date(10),
	() => new Map(),
	() => new Map([['a', 'x']]),
	() => Object.assign(new Map(), { a: 'x' }),
	() => new Map([['b', 'x']]),
	() => new Map([['a', 'y']]),
	() =>
		new Map([
			['a', 'x'],
			['b', 'y'],
		]),
	() =>
		new Map([
			['a', 'y'],
			['b', 'x'],
		]),
	() => new Set(),
	() => new Set(['a']),
	() => new Set(['b']),
	() => new Set(['a', 'b']),
	() => new Error('oops'),
	() => new Error('nope'),
];

export const uniqueValueFactories: (() => unknown)[] = [
	() => Symbol(),
	() => Symbol('foo'),
	() => ({ [Symbol('unique')]: 'bar' }),
];

export const allValueFactories = [
	...primitiveValueFactories,
	...standardValueFactories,
	...uniqueValueFactories,
];
