name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_and_test_14_debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Test
        run: |
          echo "install" && npm install
          echo "A" && ./src/bin/run.mjs src
          echo "B" && node ./src/bin/run.mjs src
          echo "C" && node ./src/build/run.mjs src
          echo "package" && ./test/run-package.sh
          echo "test" && npm test

  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { node: '16' }
          - { node: '17' }
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Test
        run: npm install-test
